-- init.sql
CREATE USER test PASSWORD 'airbyte';

GRANT USAGE ON SCHEMA public TO test;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO test;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO test;
